### ISSUE TITLE
=====

### ISSUE THREAD

**Issue by nister6000** [gigabit101/Condensed-Block-Mod-Reborn#1]
Hello in newest version (1.0.6) there is 6 = before all chat messages.

**Comment by gigabit101** [comment]
This dose not seem to be my side, Its more than likely from another mod installed as I dont touch or use any of the chat code at all

**Comment by nister6000** [comment]
hmm strange but this happen only in version 1.0.6, in 1.0.5 its okay.

**Comment by gigabit101** [comment]
well as I said I don't touch anything to do with chat and 1.0.5 - 1.0.6 was just a new Block and adding some use to a few of the existing blocks

**Comment by gigabit101** [comment]
Dam Its my problem I will fix tonight I there is some issues with my en_US.lang file caused by a merge on the repo

**Comment by gigabit101** [comment]
Fixed in 1.0.7 Thanks for the report :+1:
