### ISSUE TITLE
Condensed Dirt X1 

### ISSUE THREAD

**Issue by Baoulettes** [gigabit101/Condensed-Block-Mod-Reborn#2]
Hello :)
We can't compresse Dirt to x1 (aka 9 dirt to form a block in Craft table)
Else everythings I tried worked fine :3

Also I have little request if you plan to do accept any, 
But do you plan to do Smelting part too?

like Condensed CobbleStones x1 become Condensed Stone x1 ? :)

**Comment by gigabit101** [comment]
I will look into the dirt issue and I like the smelting Idea expect to see it soon ;)

**Comment by gigabit101** [comment]
Ok there is no issue my side with the dirt recipes.
Try resetting the CbmReborn.cfg.
Smelting Recipes have been added get it here. 
http://minecraft.curseforge.com/mc-mods/225226-condensed-block-mod-reborn/files
