### ISSUE TITLE
Many bugs found.

### ISSUE THREAD

**Issue by Ashymad** [gigabit101/Condensed-Block-Mod-Reborn#3]
While playing on server with friends, we've found multiple bugs:
1. There is no recipe for Condensed Dirt X1, it is impossible to craft it. NEI doesn't show it as well.
2. It's impossible to craft Condensed Bones X1. NEI shows that its crafted with 9xMelon, but this just gives you Condensed Melon X1.
3. It's impossible to craft Condensed Wheat X1. This obviously doesn't work as 9xWheat gives you Hay Bale. The block should be changed to Condensed Hay Bale.
4. Smelting any X1 condensed block gives you output in Condesed X2 form. For example: smelting Condensed Cobble X1 gives you Condensed Stone X2. Smelting other concentrations works as intended.
5. Condensed Glass allows you to see through any opaque block that's connected to it. This allows for X-Ray, as well as looks quite bad.

Finally, these are not bugs, but they seem rather weird:
1. Although there is Condensed Potato, there isn't Condensed Baked Potato.
2. The only type of condensed wood is oak wood (Condensed Logs).

Just to be sure I've checked the bugs on clean MC 1.7.10 with only Forge 10.13.4.1558 and CbmReborn 1.0.8. I have Java 8u73 x64 on Windows 8.1 x64.

**Comment by gigabit101** [comment]
This mod is long since dead I might rewrite for 1.8 but this was one of my first mods and very badly coded If you wish to use It I recommend Minetweeker to fix any recipe issues
